package cli

const (
	Linux       string = "Linux"
	MacOSX      string = "Mac OS X"
	MacOS       string = "macOS"
	Iphone      string = "iPhone OS"
	Windows     string = "Windows"
	Interix     string = "Interix"
	Haiku       string = "Haiku"
	FreeBSD     string = "FreeBSD"
	DragonFly   string = "DragonFly"
	Darwin      string = "Darwin"
	SunOS       string = "SunOS"
	illumos     string = "illumos"
	Solaris     string = "Solaris"
	MINIX       string = "MINIX"
	AIX         string = "AIX"
	IRIX        string = "IRIX"
	FreeMiNT    string = "FreeMiNT"
	Ironclad    string = "Ironclad"
	OSF1        string = "OSF1"
	digitalUNIX string = "digitalUNIX"
	GNU         string = "GNU"
	Bitrig      string = "Bitrig"
	BSD         string = "BSD"
	CYGWIN      string = "CYGWIN"
	MSYS        string = "MSYS"
	MINGW       string = "MINGW"
	Windows_NT  string = "Windows_NT"
	RavynOS     string = "ravynOS"
	NetBSD      string = "NetBSD"
	OpenBSD     string = "OpenBSD"
)
